# Site settings
name: Meet Patel
title: Meet | Full Stack Web Developer 
description: Design-minded front-end & back-end websites developer focused on building beautiful interfaces and experiences
url: https://meetpateltech.github.io/
baseurl: ''
email: meetpatel.mn@gmail.com
cover: https://meetpateltech.github.io/img/og.png
logo: https://meetpateltech.github.io/img/emojis/technologist.png
resume: https://meetpateltech.github.io/resume.pdf
social:
  - title: email
    url: mailto:meetpatel.mn@gmail.com
  - title: twitter
    url: https://twitter.com/mn_google
  - title: instagram
    url: https://instagram.com/patelmn23
  - title: codepen
    url: https://codepen.io/meetpateltech
  - title: github
    url: https://github.com/meetpateltech
  - title: linkedin
    url: https://www.linkedin.com/in/meet-patel-6716b5242

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
